---
# defaults file for rems-mediator
rems_admin_user: admin
rems_admin_api_key: DEFAULT_IS_INSECURE
rems_postgres_user: rems
rems_postgres_password: DEFAULT_IS_INSECURE
rems_public_url: "https://{{ inventory_hostname }}/"
gen3_server_url: https://data.acdc.ozheart.org
gen3_auth_config: |-
  '{
      "api_key": "OBTAINED_FROM_GEN3",
      "key_id": "aaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
  }'
gen3_user_config_file: "/etc/gen3/users.yaml"
rems_server_url: "{{ rems_public_url }}"
rems_user_id: admin
rems_api_key: DEFAULT_IS_INSECURE
rems_organization_id: biocommons
rems_license_id: 1
rems_user_roles:
  - user: http://cilogon.org/serverB/users/41516102
    role: user-owner
  - user: http://cilogon.org/serverB/users/41516102
    role: owner

_rems_environment:
  POSTGRES_USER: "{{ rems_postgres_user }}"
  POSTGRES_PASSWORD: "{{ rems_postgres_password }}"
  GEN3_SERVER_URL: "{{ gen3_server_url }}"
  GEN3_AUTH_CONFIG: '{{ gen3_auth_config }}'
  GEN3_USER_CONFIG_FILE: "{{ gen3_user_config_file }}"
  REMS_SERVER_URL: "{{ rems_server_url }}"
  REMS_USER_ID: "{{ rems_user_id }}"
  REMS_API_KEY: "{{ rems_api_key }}"
  REMS_ORGANIZATION_ID: "{{ rems_organization_id }}"
  REMS_LICENSE_ID: "{{ rems_license_id }}"
